version: "2.1"

services:
  go-docker-dev:
    image: go-docker-dev
    build:
      context: .
      dockerfile: Dockerfile_debug
    volumes:
      - "./:/go/src/app"
    links:
      - mongo
    ports:
      - 8080:8080

  mongo:
    image: mongo
    ports:
      - 27017:27017
